### ISSUE TITLE
How to enable exclusive collection in Benevolent Sprites

### ISSUE THREAD

**Issue by erney519** [Aidanamite/Benevolent-Sprites#2]
Extra Settings API is already installed
But when I open console there only three commands about Sprites 
clearSpriteData、getSpriteData、printItemSprites
No command found to enable exclusive collection

**Comment by Aidanamite** [comment]
Please make sure to read the mod page before reporting issues:
> Using the [Extra Settings API](https://www.raftmodding.com/mods/extra-settings-api) you can set some of the sprites to "exclusive collection"
