### ISSUE TITLE
[Suggestion] Benevolvent Sprites use Manual Dredgers

### ISSUE THREAD

**Issue by Legende04** [Aidanamite/Benevolent-Sprites#4]
The Title is pretty self explainatory :)
I love your mod, and would appreciate that feature

I was wondering wether it is normal that the Sprites only use the electric dredgers and not the manual ones?
If it is intended maybe add an option in the settings wether to allow sprites using them or not
Thank you :)

**Comment by Aidanamite** [comment]
as far as i know the sprites can collect from manual dredgers. none of their code is specific to either type

**Comment by Legende04** [comment]
weird, imma try again and come back if it doesn't work then
ty

**Comment by Legende04** [comment]
I tried again, but it seems like the sprite is only collecting the Items I manually dredged up, but not dredging itself or is it suppost to be another one, not the cleaner?

**Comment by Aidanamite** [comment]
while trouble shooting your other issue i've confirmed that it will collect from the manual dredger but the sprite will not drop the the dredger so i'll need to set it up to do that

**Comment by Legende04** [comment]
okay, but is it intended to not drop it, or will you consider fixing it?
or maybe add an option wether to allow it or not

**Comment by Aidanamite** [comment]
it's not "intended" to not drop it, i just never programmed it to do so. but i can add that fairly easily

**Comment by Legende04** [comment]
that would be awesome, thank you bro :)

**Comment by Aidanamite** [comment]
ok so... interesting behaviour with the manual dredger... there is no cooldown on raising the dredger back. there is no cooldown on any part of the dredger other than the time it takes for the dredger to finish rising back up. which means if i program the sprite accordingly then a cleaner sprite would just sit at the dredger and spam the bucket going up and down until it gets an item

**Comment by Aidanamite** [comment]
i initially assumed that the dredger would attempt to collect an item every few seconds or a few times a second and then you could raise it back up once it has an item. however the way it actually works is just that each time you raise the bucket it has a chance of getting an item

**Comment by Aidanamite** [comment]
it would appear that the electric dredger works the same, just that it spends battery power to drop and raise the bucket until it gets something... which means that if i were to allow the cleaner sprite to drop and raise the bucket it would make manual dredgers better than electric

**Comment by Aidanamite** [comment]
I've decided: the main point of the sprites mod is to enable automation on things that could not already be automated. Given that there is a fully automatic way to raise and lower the dredger, i don't think i should enable the sprites to also do that
